### ISSUE TITLE
InitSensor() returns error when using VL53L0x_DEFAULT_DEVICE_ADDRESS

### ISSUE THREAD

**Issue by beegee-tokyo** [stm32duino/VL53L0X#16]
_**Library version:**_ 2.0.0
_**IDE**_: PlatformIO or ArduinoIDE, both show the same error
_**BSP:**_ PIO Nordic nRF52  Arduino STM32Duino

_**Bug:**_ **`InitSensor(0x52);`** always returns error **`VL53L0X_ERROR_INVALID_PARAMS`**

_**Code to show error:**_
```cpp
	int status = tof_sensor.InitSensor(0x52);
	if (status)
	{
		Serial.println("Failed to detect and initialize sensor!");
	}
```

_**Cause:**_
Problem is in the code of **`InitSensor()`** in _**vl53l0x_class.cpp**_:
```cpp
      if(NewAddr!=VL53L0x_DEFAULT_DEVICE_ADDRESS)
      {
         status=SetDeviceAddress(NewAddr);
         if(status)
         {
            printf("Failed to change I2C address!\n\r");
            return status;
         }
      }
      else
      {
         printf("Invalid new address!\n\r");
         return VL53L0X_ERROR_INVALID_PARAMS;
      }
```
Will always return an **`VL53L0X_ERROR_INVALID_PARAMS`** if **`InitSensor(0x52)`** is called.

**Comment by cparata** [comment]
Hi @beegee-tokyo ,
thanks for the submission. You are right and I fixed the issue in the "main" branch adding a new release of the library with the fix.
Thanks for the contribution.
Best Regards,
Carlo

**Comment by beegee-tokyo** [comment]
👍
