### ISSUE TITLE
Is it possible to modify this library for arduino boards too?

### ISSUE THREAD

**Issue by Gomezzzzz** [stm32duino/VL53L0X#6]

**Comment by cparata** [comment]
Which Arduino board do you want to use? Actually, the library should work also with whatever Arduino board. You just need to adjust the sample sketch for your use case.

**Comment by Gomezzzzz** [comment]
I use Arduino Nano and sometimes Mega.

**Comment by cparata** [comment]
Ok, thanks. What is instead the board with VL53L0X component that you are using? Is the X-NUCLEO-53L0A1 shield?

**Comment by Gomezzzzz** [comment]
Oh, I think it's Chinese noname. :( 
![vl53l0x-flight-tof-breakout-940nm-gy-vl53l0xv2](https://user-images.githubusercontent.com/25661921/40043879-75067b20-582e-11e8-8d64-0b6275a16e29.jpg)
![vl53l0x-flight-tof-breakout-940nm-gy-vl53l0xv2_1](https://user-images.githubusercontent.com/25661921/40043583-94cb9b12-582d-11e8-91da-af23f70a3452.jpg)

**Comment by cparata** [comment]
Ok, I fixed an issue on the library (UNUSED macro was not defined for Arduino boards). Now you can try to run the Arduino_Nano_VL53L0X_DataLogTerminal sketch attached to this post but you need to adjust the Wire and the pins XSHUT, GPIO1 definition. I suppose that Wire instance is "Wire" of the Nano, XSHUT is pin 5 of the Nano and GPIO1 is pin 6 of the Nano. So you need to physically connect these pins to the Nano using some wires. Let me know if it works on your side. Unfortunately I do not have an Arduino Nano and your chinese board of VL53L0X to test your setup.
Regards,
Carlo
[Arduino_Nano_VL53L0X_DataLogTerminal.txt](https://github.com/stm32duino/VL53L0X/files/2004135/Arduino_Nano_VL53L0X_DataLogTerminal.txt)

**Comment by Gomezzzzz** [comment]
Wow! Thank you so much! It's working now!

**Comment by cparata** [comment]
Great! I will close this issue and I will create a new tag of the library with this patch and some tips to get the library working also with Arduino boards.
